name: Build OutfitConverter

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    
    strategy:
      matrix:
        configuration: [Release]
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup CMake
      uses: lukka/get-cmake@latest
    
    - name: Configure CMake
      run: |
        cmake -B build -G "Visual Studio 17 2022" -A x64
      shell: cmd
    
    - name: Build Project (Release)
      run: |
        cmake --build build --config Release --parallel 4
      shell: cmd
      timeout-minutes: 20
    
    - name: Verify Build Output
      run: |
        if exist "build\bin\Release\OutfitConverter.exe" (
          echo Build successful!
          dir build\bin\Release
        ) else (
          echo Build failed - executable not found
          exit 1
        )
      shell: cmd
    
    - name: Create Archive
      run: |
        cd build\bin\Release
        7z a -tzip ..\..\..\OutfitConverter-x64.zip OutfitConverter.exe
        cd ..\..\..
        dir OutfitConverter-x64.zip
      shell: cmd
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: OutfitConverter-Release-x64
        path: build/bin/Release/OutfitConverter.exe
        retention-days: 30
        compression-level: 9
    
    - name: Upload Release Package
      uses: actions/upload-artifact@v4
      with:
        name: OutfitConverter-Release-Package
        path: OutfitConverter-x64.zip
        retention-days: 90
        compression-level: 9

  create-release:
    needs: build-windows
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    timeout-minutes: 10
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Download Release Package
      uses: actions/download-artifact@v4
      with:
        name: OutfitConverter-Release-Package
        path: release
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: OutfitConverter ${{ github.ref_name }}
        body: |
          ## GTA V Outfit Converter ${{ github.ref_name }}
          
          **Credit to @sizrox on Discord**
          
          ### ✨ Features
          - Convert between Cherax, YimMenu, Lexis, and Stand formats
          - Real-time memory editing for GTA V
          - Beautiful dark purple UI theme
          - Built-in outfit editor
          
          ### 📥 Download
          - **OutfitConverter-x64.zip** - Windows 64-bit (Recommended)
          
          ### 📋 Requirements
          - Windows 10/11 (64-bit)
          - Visual C++ Redistributable 2019+
          - GTA V (for memory editing)
          
          ### 🚀 Quick Start
          1. Download and extract the ZIP file
          2. Run `OutfitConverter.exe`
          3. Load an outfit file or attach to GTA V
          
          ### ⚠️ Important
          Use at your own risk. This tool is for educational purposes only.
          
        files: release/*.zip
        draft: false
        prerelease: false
