name: Build OutfitConverter

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3
    
    - name: Setup CMake
      uses: lukka/get-cmake@latest
    
    - name: Configure CMake
      run: |
        cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{matrix.configuration}}
    
    - name: Build Project
      run: |
        cmake --build build --config ${{matrix.configuration}} --parallel
    
    - name: Create Archive
      if: matrix.configuration == 'Release'
      run: |
        cd build/bin/${{matrix.configuration}}
        7z a -tzip ../../../OutfitConverter-x64.zip *.exe
      shell: cmd
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: OutfitConverter-${{matrix.configuration}}-x64
        path: |
          build/bin/${{matrix.configuration}}/*.exe
        retention-days: 30
    
    - name: Upload Release Package
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
        name: OutfitConverter-Release-Package
        path: OutfitConverter-x64.zip
        retention-days: 90

  create-release:
    needs: build-windows
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Download Release Package
      uses: actions/download-artifact@v3
      with:
        name: OutfitConverter-Release-Package
        path: release
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: OutfitConverter ${{ github.ref_name }}
        body: |
          ## GTA V Outfit Converter ${{ github.ref_name }}
          
          **Credit to @sizrox on Discord**
          
          ### Features
          - Convert between Cherax, YimMenu, Lexis, and Stand formats
          - Real-time memory editing
          - Dark purple UI theme
          - Outfit editor
          
          ### Download
          - **OutfitConverter-x64.zip** - Windows 64-bit
          
          ### Requirements
          - Windows 10/11 (64-bit)
          - Visual C++ Redistributable 2019+
          
        files: release/*.zip
        draft: false
        prerelease: false
